inputs:
    input0:
        source: RTOS_CAM
        width: 1920
        height: 1080
        sensor-name: imx390
        channel-mask: 00000001
        viss-dcc-path: /opt/imaging/imx390/linear/dcc_viss.bin
        ldc-dcc-path: /opt/imaging/imx390/linear/dcc_ldc.bin
    input1:
        source: RAW_IMG
        width: 1280
        height: 720
        format: NV12
models:
    model0:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz_threshold: 0.6
outputs:
    output0:
        sink: RTOS_DISPLAY
        width: 1920
        height: 1080
    output1:
        sink: LINUX_DISPLAY
        width: 1920
        height: 1080
flows:
    flow0:
        pipeline: [input1,model0,output0]
        mosaic:
            - [320,150,1280,720]